project_name: gateway-tic
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
builds:
  - binary: gateway-tic
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm64
      - amd64
      - arm
    # GOARM to build for when GOARCH is arm.
    # For more info refer to: https://golang.org/doc/install/source#environment
    #
    # Default: [ 6 ]
    goarm:
      - "6"
      - "7"

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Runtime.Goos }}_{{ .Runtime.Goarch }}"

# snapshot:
#   name_template: "{{ .ProjectName }}_dev-{{.ShortCommit}}_{{ .Runtime.Goos }}_{{ .Runtime.Goarch }}"

checksum:
  name_template: 'checksums.txt'
